apiVersion: v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app-container
          image: notes-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo:27017/notesdb"
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080